#!/usr/bin/env python

#This script is a work in progress planning to Randomizin your mac addres and printing it.

import subprocess
subprocess.call("ifconfig eth0 down", shell=True)
subprocess.call("ifconfig eth0 hw ether 44:41:78:15:45:96", shell=True)
subprocess.call("ifconfig eth0 up", shell=True)
