#!/usr/bin/env python

import subprocess
import optparse

def get_argument():
    parser = optparse.OptionParser()
    parser.add_option("-i", dest="interface", help="interface to change your MAC address")
    parser.add_option("-m", dest="new_mac", help="to chance your Mac address ")
    return parser.parse_args()

def change_mac(interface, new_mac):
    print(" changing MAC address for " + interface + " to " + new_mac)

    subprocess.call(["ifconfig", interface, "down"])
    subprocess.call(["ifconfig", interface, "hw", "ether", new_mac])
    subprocess.call(["ifconfig", interface, "up"])

(options, get_argument) = get_argument()
change_mac(options.interface, options.new_mac)
